# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 'Bonnie 个人博客'
subtitle: ''
description: '欢迎来到我的个人博客！这是一个专属于学习和进步的小天地，记录着我在软件开发领域的学习探索、技能提升和个人成长的点滴。在这里，你将找到我对知识的追求，对新事物的探索，以及在不断挑战自我的过程中积累的经验分享。让我们一同踏上知识之旅，共同成长，探索更广阔的学习天地。'
keywords: '个人博客、学习、进步、知识追求、技能提升、学术探索、个人成长、经验分享'
author: 'Bonnie Chen'
language:
    - zh-CN
    - en
timezone: 'Asia/Shanghai'
avatar: /images/avatar.png
favicon: /images/avatar.png
# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://bonnie-dot.github.io
permalink: posts/:abbrlink.html
permalink_defaults:
pretty_urls:
    trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
    trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
    enable: true # Open external links in new tab
    field: site # Apply to the whole site
    exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
    prependRoot: true
    postAsset: true
relative_link: false
future: true
syntax_highlighter: highlight.js
prismjs:
    preprocess: true
    line_number: true
    tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
    path: ''
    per_page: 10
    order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Themes: https://hexo.io/themes/
theme: stellar
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/bonnie-dot/bonnie-dot.github.io
  branch: main
abbrlink:
    alg: crc32 #算法，支持crc16(default)和crc32
    rep: hex #进制，支持dec(default)和hex
    drafts: false #true：对草稿也进行处理，false：不处理草稿。默认为false
    # 从目录树生成类别
    # depth: 您想生成的目录树的最大深度, 需要大于0
    auto_category:
        enable: true #默认为 true
        depth: #默认为 3
        over_write: false
    auto_title: false #启用自动标题，它可以按路径自动填充标题
    auto_date: false #启用自动日期，可以按今天的时间自动填写日期
    force: false #启用Force模式，在这种模式下插件将忽略缓存，并为每一篇文章计算生成永久链接，即使它已经有了永久链接。这个设置只会更新永久链接，而不是更新其他前置变量。
